In [18]:
import pandas as pd
import numpy as np
import openpyxl

df = pd.read_excel("ProjetoLogisticaData.xlsx")
df_filtrado = df[df["Tipo_Local"] == "URF"]
display(df_filtrado)

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
0,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0130151 - CACERES,-,-,URF,0130151 - CACERES
1,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145100 - MUNDO NOVO,64,35,URF,0145100 - MUNDO NOVO
2,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145200 - CORUMBA,6322760,4924826,URF,0145200 - CORUMBA
3,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0145300 - PONTA PORA,53703,32125,URF,0145300 - PONTA PORA
4,Acordo Agrícola OMC e Pescados,Exportacao,2015.0,(1º Nível) CARNES,(URF) 0147600 - ALF - CORUMBÁ,-,-,URF,0147600 - ALF - CORUMBÁ
...,...,...,...,...,...,...,...,...,...
2598,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017701 - IRF - CHUÍ,262317068,70240574,URF,1017701 - IRF - CHUÍ
2599,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017800 - ALF - PORTO ALEGRE,128546,19740,URF,1017800 - ALF - PORTO ALEGRE
2600,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017801 - IRF - AEROPORTO INTERNACIONAL ...,-,-,URF,1017801 - IRF - AEROPORTO INTERNACIONAL SALGAD...
2601,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 1017900 - ALF - SANTANA DO LIVRAMENTO,-,-,URF,1017900 - ALF - SANTANA DO LIVRAMENTO
2602,Agronegócio,Exportacao,2025.0,(1º Nível) CARNES,(URF) 9999999 - NAO INFORMADO,16687,55,URF,9999999 - NAO INFORMADO

In [19]:
df_filtrado.to_excel("Nova_planilha.xlsx", index = False)

In [ ]:
# df_novo = pd.read_excel("Nova_planilha.xlsx")
# df_novo.loc[:, 'Peso_KG'] = df_novo['Peso_KG'].replace("-", 0) 
# for data, df in df_novo.groupby(["Regiao_UF_URF", "Agrupamento"]):
#     df: pd.DataFrame display(df)

df_novo = pd.read_excel("Nova_planilha.xlsx")

df_novo.loc[:, 'Peso_KG'] = df_novo['Peso_KG'].replace("-", 0)

df_novo = pd.read_excel("Nova_planilha.xlsx")

df_novo.loc[:, 'Peso_KG'] = df_novo['Peso_KG'].replace("-", 0)

# normaliza a coluna (remove espaços extras e deixa minúsculo)
df_novo["Regiao_UF_URF"] = df_novo["Regiao_UF_URF"].str.strip().str.lower()

regioes_filtro = [
    "(urf) 1010200 - pelotas",
    "(urf) 1010252 - jaguarão",
    "(urf) 1010253 - bagé",
    "(urf) 1010300 - santa maria",
    "(urf) 1010400 - passo fundo",
    "(urf) 1010600 - caxias do sul",
    "(urf) 1010700 - novo hamburgo",
    "(urf) 1010851 - porto mauá",
    "(urf) 1010852 - porto xavier",
    "(urf) 1010900 - uruguaiana",
    "(urf) 1010951 - itaqui",
    "(urf) 1010953 - são borja",
    "(urf) 1010954 - barra do quaraí",
    "(urf) 1010955 - quaraí",
    "(urf) 1011100 - santa cruz do sul",
    "(urf) 1015400 - porto alegre",
    "(urf) 1015500 - chuí",
    "(urf) 1015600 - santana do livramento",
    "(urf) 1017600 - aeroporto salgado filho (porto alegre)",
    "(urf) 1017700 - porto de rio grande"
]

df_novo = df_novo[df_novo["Regiao_UF_URF"].isin(regioes_filtro)]

for data, df in df_novo.groupby(["Regiao_UF_URF", "Agrupamento"]):
    display(df)     
df_novo = df_novo[df_novo["Regiao_UF_URF"].isin(regioes_filtro)]

for data, df in df_novo.groupby(["Regiao_UF_URF", "Agrupamento"]):
    df: pd.DataFrame
    display(df)

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
71,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,33829835,10472798,URF,1010900 - URUGUAIANA
155,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,39483552,16868274,URF,1010900 - URUGUAIANA
239,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,24419315,8534603,URF,1010900 - URUGUAIANA
323,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
407,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
491,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
575,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
659,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
743,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
827,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
911,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
995,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,33829835,10472798,URF,1010900 - URUGUAIANA
1079,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,39483552,16868274,URF,1010900 - URUGUAIANA
1163,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,24419315,8534603,URF,1010900 - URUGUAIANA
1247,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1331,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1415,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1499,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1583,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1667,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1751,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1835,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1862,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
74,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
158,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
242,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
326,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
410,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
494,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
578,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
662,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
746,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
830,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
914,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
998,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
1082,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
1166,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
1250,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1334,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1418,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1502,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1586,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1670,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1754,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1838,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1865,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
78,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
162,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
246,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
330,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
414,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
498,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
582,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
666,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
750,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
834,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
918,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1002,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
1086,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
1170,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
1254,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
1338,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
1422,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
1506,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
1590,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
1674,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
1758,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
1842,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE
1869,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
71,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,33829835,10472798,URF,1010900 - URUGUAIANA
155,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,39483552,16868274,URF,1010900 - URUGUAIANA
239,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,24419315,8534603,URF,1010900 - URUGUAIANA
323,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
407,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
491,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
575,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
659,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
743,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
827,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
911,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
995,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,33829835,10472798,URF,1010900 - URUGUAIANA
1079,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,39483552,16868274,URF,1010900 - URUGUAIANA
1163,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,24419315,8534603,URF,1010900 - URUGUAIANA
1247,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1331,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1415,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1499,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1583,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1667,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1751,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1835,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA
1862,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1010900 - uruguaiana,-,0,URF,1010900 - URUGUAIANA

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
74,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
158,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
242,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
326,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
410,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
494,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
578,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
662,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
746,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
830,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
914,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
998,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,25495585,9661444,URF,1015600 - SANTANA DO LIVRAMENTO
1082,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,24036927,10331830,URF,1015600 - SANTANA DO LIVRAMENTO
1166,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,29065264,10719293,URF,1015600 - SANTANA DO LIVRAMENTO
1250,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1334,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1418,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1502,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1586,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1670,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1754,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1838,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO
1865,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1015600 - santana do livramento,-,0,URF,1015600 - SANTANA DO LIVRAMENTO

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
78,Acordo Agrícola OMC e Pescados,Exportacao,2015,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
162,Acordo Agrícola OMC e Pescados,Exportacao,2016,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
246,Acordo Agrícola OMC e Pescados,Exportacao,2017,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
330,Acordo Agrícola OMC e Pescados,Exportacao,2018,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
414,Acordo Agrícola OMC e Pescados,Exportacao,2019,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
498,Acordo Agrícola OMC e Pescados,Exportacao,2020,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
582,Acordo Agrícola OMC e Pescados,Exportacao,2021,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
666,Acordo Agrícola OMC e Pescados,Exportacao,2022,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
750,Acordo Agrícola OMC e Pescados,Exportacao,2023,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
834,Acordo Agrícola OMC e Pescados,Exportacao,2024,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
918,Acordo Agrícola OMC e Pescados,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE

,Agrupamento,Transacao,Ano,Produto,Regiao_UF_URF,Valor_USD,Peso_KG,Tipo_Local,Local
1002,Agronegócio,Exportacao,2015,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,954855773,485784020,URF,1017700 - PORTO DE RIO GRANDE
1086,Agronegócio,Exportacao,2016,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,812252683,442010608,URF,1017700 - PORTO DE RIO GRANDE
1170,Agronegócio,Exportacao,2017,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,822709279,409190491,URF,1017700 - PORTO DE RIO GRANDE
1254,Agronegócio,Exportacao,2018,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,840885987,442083878,URF,1017700 - PORTO DE RIO GRANDE
1338,Agronegócio,Exportacao,2019,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1012198441,486725696,URF,1017700 - PORTO DE RIO GRANDE
1422,Agronegócio,Exportacao,2020,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1136343434,531338603,URF,1017700 - PORTO DE RIO GRANDE
1506,Agronegócio,Exportacao,2021,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1063427179,482999234,URF,1017700 - PORTO DE RIO GRANDE
1590,Agronegócio,Exportacao,2022,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1122084936,480680521,URF,1017700 - PORTO DE RIO GRANDE
1674,Agronegócio,Exportacao,2023,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1273713767,571383157,URF,1017700 - PORTO DE RIO GRANDE
1758,Agronegócio,Exportacao,2024,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1276345725,575897435,URF,1017700 - PORTO DE RIO GRANDE
1842,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE
1869,Agronegócio,Exportacao,2025,(1º Nível) CARNES,(urf) 1017700 - porto de rio grande,1120114746,454125456,URF,1017700 - PORTO DE RIO GRANDE